### ISSUE TITLE
Compatibility issue on Event parameter of Upnp_FunPtr

### ISSUE THREAD

**Issue by ffontaine** [mrjimenez/pupnp#63]
Dear Marcelo,

There is a compatibility issue between upnp in version 1.6.x and 1.8.x because in libupnp 1.6.x, the Event in Upnp_FunPtr was a simple void: https://github.com/mrjimenez/pupnp/blob/branch-1.6.x/upnp/inc/upnp.h
```
typedef int (*Upnp_FunPtr)(
	/*! [in] .*/
	Upnp_EventType EventType,
	/*! [in] .*/
	void *Event,
	/*! [in] .*/
	void *Cookie);
```
However, it was changed to a const void* in 1.8.x: https://github.com/mrjimenez/pupnp/blob/master/upnp/inc/Callback.h:

```
typedef int (*Upnp_FunPtr)(
	/*! [in] .*/
	Upnp_EventType EventType,
	/*! [in] .*/
	const void *Event,
	/*! [in] .*/
	void *Cookie);
```

As a result of this change, vlc fails to build with libupnp-1.8 even with compat functions.
@mrjimenez what is your suggestion? Should we add a const in 1.6.x (and breaks older applications) or remove it from 1.8.x ?

Fabrice

**Comment by ukleinek** [comment]
I'd say the `const` there is good, and so we should keep it in 1.8. But adding it to 1.6 (and so possibly breaking stuff) is not worth it.

Which vlc version do you try to build? AFAIK vlc in Debian (based on 2.2.8) builds fine with both upnp 1.6 and 1.8.

**Comment by ffontaine** [comment]
The issue was raised when trying to build vlc 2.2.8 with libupnp 1.6.24 in buildroot. Which version of libupnp is used in debian?
First, the following upstream patch must be applied: https://github.com/videolan/vlc/commit/f9c5a343f1a8cad9c2c153f9c05e4e7201675a43#diff-2e66eb8b4fb06845a6426bd4a541d2f7
But even after this patch, the following error is raised:
```
services_discovery/upnp.cpp: In function 'int Open(vlc_object_t*)':
services_discovery/upnp.cpp:174:71: error: invalid conversion from 'int
(*)(Upnp_EventType, UpnpEventPtr, void*) {aka int (*)(Upnp_EventType_e,
const void*, void*)}' to 'Upnp_FunPtr {aka int (*)(Upnp_EventType_e,
void*, void*)}' [-fpermissive]
     i_res = UpnpRegisterClient( Callback, p_sd, &p_sys->client_handle );
```
However, I found that the issue was that I badly applied the upstream patch. vlc 2.2.8 defines the following if upnp version is above 1.8 (or 1.6.23 after applying upstream patch):

```
#else
typedef const void* UpnpEventPtr;
#endif
```
This should be updated as done in upnp.hpp of the master branch of vlc:
```
#elif UPNP_VERSION < 10800
typedef void* UpnpEventPtr;
#else
typedef const void* UpnpEventPtr;
#endif
```

I will patch vlc 2.2.8 in buildroot and we can definetly close this issue. Thanks for your help.

**Comment by bkuhls** [comment]
@ffontaine: FTR: Debian includes exactly the patch you proposed: https://sources.debian.org/src/vlc/2.2.8-2/debian/patches/0012-Fix-UpnpEventPtr-typedef-for-versions-before-1.8.0.patch/

**Comment by barracuda156** [comment]
Is it back to `void*` in 1.18.5? I got the error with VLC2 now, and changing from `typedef const void* UpnpEventPtr;` to `typedef void* UpnpEventPtr;` fixed it.

**Comment by mrjimenez** [comment]
> Is it back to `void*` in 1.18.5? I got the error with VLC2 now, and changing from `typedef const void* UpnpEventPtr;` to `typedef void* UpnpEventPtr;` fixed it.

Yes. Unfortunately, `const` is wrong in this case.
